contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #crispr channel"
    url: https://nfcore.slack.com/channels/crispr
    about: Discussion about the nf-core/crispr pipeline
